//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class HospitalRollCall {
    
    private HospitalRollCallHospital[] hospitalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hospital")]
    public HospitalRollCallHospital[] Hospital {
        get {
            return this.hospitalField;
        }
        set {
            this.hospitalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class HospitalRollCallHospital {
    
    private string hospitalNameField;
    
    private string callSignField;
    
    private string nameField;
    
    private bool trafficField;
    
    private bool packetField;
    
    private bool hosEqField;
    
    private bool printerField;
    
    private bool testedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hospitalName {
        get {
            return this.hospitalNameField;
        }
        set {
            this.hospitalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string callSign {
        get {
            return this.callSignField;
        }
        set {
            this.callSignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool traffic {
        get {
            return this.trafficField;
        }
        set {
            this.trafficField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool packet {
        get {
            return this.packetField;
        }
        set {
            this.packetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hosEq {
        get {
            return this.hosEqField;
        }
        set {
            this.hosEqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool printer {
        get {
            return this.printerField;
        }
        set {
            this.printerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool tested {
        get {
            return this.testedField;
        }
        set {
            this.testedField = value;
        }
    }
}
