//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PrintConfig {
    
    private PrintConfigReceivedSentSettings[] receivedSentSettingsField;
    
    private string printerNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReceivedSentSettings")]
    public PrintConfigReceivedSentSettings[] ReceivedSentSettings {
        get {
            return this.receivedSentSettingsField;
        }
        set {
            this.receivedSentSettingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PrinterName {
        get {
            return this.printerNameField;
        }
        set {
            this.printerNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PrintConfigReceivedSentSettings {
    
    private PrintConfigReceivedSentSettingsCopyDestinations[] copyDestinationsField;
    
    private bool receivedPrintField;
    
    private bool printField;
    
    private byte copyCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CopyDestinations")]
    public PrintConfigReceivedSentSettingsCopyDestinations[] CopyDestinations {
        get {
            return this.copyDestinationsField;
        }
        set {
            this.copyDestinationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReceivedPrint {
        get {
            return this.receivedPrintField;
        }
        set {
            this.receivedPrintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Print {
        get {
            return this.printField;
        }
        set {
            this.printField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte copyCount {
        get {
            return this.copyCountField;
        }
        set {
            this.copyCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PrintConfigReceivedSentSettingsCopyDestinations {
    
    private string destinationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
}
